baseURL = "https://upbeat-hopper-420566.netlify.com/"
languageCode = "en-us"
title = "Via Papier"
theme = "harbor"
author = "Max Greive"
paginate = 3
DefaultContentLanguage = "de"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "Via Papier"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "facebook"
  name = "fb.me/viapapier"
  icon = "fab fa-facebook"
  url = "https://facebook.com/viapapier"
  weight = 3

[[params.nav]]
  identifier = "instagram"
  name = "instagr.am/viapapier"
  icon = "fab fa-instagram"
  url = "https://instagram.com/viapapier"
  weight = 3

[[params.nav]]
  identifier = "download"
  name = "Download"
  icon = "fas fa-download"
  url = "#download"
  weight = 3

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "via-papier-logo.png"
    alt = "Logo"

[languages]
  [languages.de]
    languageName = "German"
    contentDir = "content"
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
  [languages.fr]
    languageName = "French"
    contentDir = "content/fr"
  [languages.es]
    languageName = "Spanish"
    contentDir = "content/es"
  [languages.nl]
    languageName = "Dutch"
    contentDir = "content/nl"
  [languages.it]
    languageName = "Italian"
    contentDir = "content/it"
  [languages.po]
    languageName = "Polish"
    contentDir = "content/po"
