baseURL = "https://upbeat-hopper-420566.netlify.com/"
languageCode = "en-us"
title = "Via Papier"
theme = "harbor"
author = "Max Greive"
paginate = 3
DefaultContentLanguage = "de"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "Via Papier"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "facebook"
  name = "fb.me/viapapier"
  icon = "fab fa-facebook-square"
  url = "https://facebook.com/viapapier"
  weight = 3
  newWindow = true

[[params.nav]]
  identifier = "instagram"
  name = "instagr.am/viapapier"
  icon = "fab fa-instagram"
  url = "https://instagram.com/viapapier"
  weight = 3
  newWindow = true

[[params.nav]]
  identifier = "download"
  name = "Download"
  icon = "fas fa-download"
  url = "#"
  class = "scroller"
  target = "#btn-download"
  weight = 3

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "via-papier-logo.png"
    alt = "Logo"
  [params.ogImage]
    url = "images/og-via-papier.png"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = "1"
    contentDir = "content"
      [languages.de.params]
        slug = "german"
  [languages.en]
    languageName = "English"
    weight = "2"
    contentDir = "content/en"
      [languages.en.params]
        slug = "english"
  [languages.fr]
    languageName = "Français"
    weight = "3"
    contentDir = "content/fr"
      [languages.fr.params]
        slug = "french"
  [languages.es]
    languageName = "Español"
    weight = "4"
    contentDir = "content/es"
      [languages.es.params]
        slug = "spanish"
  [languages.nl]
    languageName = "Nederlands"
    weight = "5"
    contentDir = "content/nl"
      [languages.nl.params]
        slug = "dutch"
  [languages.it]
    languageName = "Italiano"
    weight = "6"
    contentDir = "content/it"
      [languages.it.params]
        slug = "italian"
  [languages.pl]
    languageName = "Polski"
    weight = "7"
    contentDir = "content/pl"
      [languages.pl.params]
        slug = "polish"
